### ISSUE TITLE
docker_validator, docker_writer, docker_bootmode and docker_generator containers won't start

### ISSUE THREAD

**Issue by paulspartan14** [lacchain/lacchain-docker#2]
Logs: 

StaticNodes file /opt/besu/data/static-nodes.json does not exist, no static connections will be created.

 main | ERROR | RocksDBKeyValueStorageFactory | Failed to retrieve the RocksDB database meta version: /opt/besu/data/DATABASE_METADATA.json (Permission denied)

4.8/opt/besu/data/DATABASE_METADATA.json (Permission denied)

Error: EACCES: permission denied, open '/validators/1/keys/key'
at Object.openSync (fs.js:454:3)
at Proxy.writeFileSync (fs.js:1247:35)
at createNodeKey (file:///app/index.js:11:6)
at file:///app/index.js:22:3
at ModuleJob.run (internal/modules/esm/module_job.js:111:37)
at async Loader.import (internal/modules/esm/loader.js:128:24)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lacchain-keygen@1.0.0 start: `node --experimental-modules ./index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lacchain-keygen@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR! /home/node/.npm/_logs/2021-04-20T04_20_53_991Z-debug.log

**Comment by NicoSerranoP** [comment]
Try doing it with admin privileges: ``` sudo ./run.sh ```
